# Generated by Django 3.2.4 on 2021-06-03 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='value',
            field=models.CharField(max_length=50),
        ),
    ]
