# Generated by Django 3.2.4 on 2021-06-08 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0004_phone_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phone',
            name='is_purchased',
        ),
    ]
